### PR TITLE
Update fastify to v3 rc1

### PR DESCRIPTION
**Pull request by anthonyringoet**
- Updated fastify dependency to v3 rc1 (for fastify/fastify#2217)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
why did you close this?

**Comment by anthonyringoet** [comment]
Thought I made a mistake because (it seems) this repo did not really need the version bump of fastify dev dependency. Still have the code here so would be able to push it back if needed.

**Comment by anthonyringoet** [comment]
Just noticed it *is* used explicitly in test.js 😄

**Comment by anthonyringoet** [comment]
Can't reopen, but commit is back now @mcollina

**Pull request closed without merging**
